### ISSUE TITLE
Trimmed zero at the end after the digit

### ISSUE THREAD

**Issue by seoromka** [ChristianRiesen/base32#28]
`Base32::decode(Base32::encode('10')) // 1`
`Base32::decode(Base32::encode('test130')) // test13`

**Comment by ChristianRiesen** [comment]
Thanks for the report. That's a really odd one. I'll have a look at it.

**Comment by samuelwilliams** [comment]
I think it has to do what is happening [on this line](https://github.com/ChristianRiesen/base32/blob/master/src/Base32.php#L108)

**Comment by afk11** [comment]
Tried the following with the above code, 'test' loses a character also
tess => tess
**test => tes**
tesu => tesu

**Comment by afk11** [comment]
I had a little look at this, inspecting the '8' test case.
correct: HA======
incorrect: H=======

    our input:
    [ 0 1 2 3 4 5 6 7 ] [ 8 9 a b c d e f ]

When outputting that second character, it's parsing from bits 5 - 9. Bits 5-7 all belong to character 0 of the input, but because in the second iteration bitLen is 3, it needs to read more data which increments n. Later determining the character to print, $n no longer refers to the character that we read from input - causing it to be >= len and, using '=' instead of the array lookup.

Here I'm subtracting 1 if $bitLen is greater than 8, indicating we're still processing the previous n - it seems to work.

            $encoded .= ($n-($bitLen>8?1:0) > $len && 0 == $val) ? '=' : static::ALPHABET[$val >> $shift];

I'll make a PR and add the '8' and test130 test cases, but we should try look for extra test fixtures from notable projects using base32 if possible

**Comment by ChristianRiesen** [comment]
I'll add a few more tests to make sure the issues as reported are covered. Thank you everyone for reporting and adding info, as well as afk11 for the quick fix 🥇

**Comment by afk11** [comment]
Wrote a brute forcer to test every 8bit, 16bit, and 32bit string https://gist.github.com/afk11/26be2ca69f34c7480cfbc6151477ff68 input. It did catch the issue when I undid the fix.. so hopefully it'll catch anything unexpected between the two implementations, or cases where `decoded result != input`

So far so good. It'll take a while.

**Comment by afk11** [comment]
That script completed and didn't turn up anything! Happy days

**Comment by ChristianRiesen** [comment]
Thank you for the extra effort! Good to know it passes the bruteforce test :)

**Comment by seoromka** [comment]
Thank you!
